version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=freescout
      - MYSQL_USER=freescout
      - MYSQL_PASSWORD=freescout
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
      - 8888:80
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
      - ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    #  - data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
      - logs:/www/logs
    #  - ./:/assets/modules/Freescout-Eventbrite-Module
    environment:
      - CONTAINER_NAME=freescout-app

      - DB_HOST=mysql
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - SITE_URL=http://localhost:8888/
      - ADMIN_EMAIL=brian.adams@lansingmakersnetwork.org
      - ADMIN_PASS=adminpass
      - ENABLE_SSL_PROXY=TRUE
      - NGINX_ENABLE_FASTCGI_HTTPS=TRUE
      - DISPLAY_ERRORS=TRUE
      - TIMEZONE=America/Detoit
    restart: always
volumes:
  logs: